on: 

 workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Custom Step
        id: step1
        uses: aviskalange/CustomActionGET@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo The id is ${{needs.job1.outputs.output1}}
