on: 

 workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: aviskalange/CustomActionGET@main
  second_job:
    # Use the output from the `hello` step
    runs-on: ubuntu-latest
    name: Secondo
    steps:
      - name: Get the output time
        id: secondo
        run: echo "The time was ${{ steps.hello.outputs.id }}"
