on: 

 workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: aviskalange/CustomActionGET@main
      - name: Hello2.0
        id : hello2
        run : echo "The id is ${{ steps.hello.outputs.id }}"
      - name: Hello3.0
        id : hello3
        run : echo "id=${{ steps.hello.outputs.id }}" >> $GITHUB_OUTPUT
    outputs:
      id: ${{ steps.hello3.outputs.id }}
  second_job:
    # Use the output from the `hello` step
    runs-on: ubuntu-latest
    name: Secondo
    steps:
      - name: Get the output time
        id: secondo
        run: echo "The id is ${{ steps.hello.outputs.id }} and ${{ needs.hello_world_job.outputs.id}}"
