on: 

 workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: aviskalange/CustomActionGET@main
      - name: Hello2.0
        id : hello2
        run : echo "The id is ${{ steps.hello.outputs.id }}"
